// styles
const fontColor = 'orange'
const fontWeight = 'bold'
const displayType = 'flex'
const displayDefault = 'none'
const blockStyle = '2px solid orange'
// uls
const firstHorizontalUl = 'fhu'
const secondHorizontalUl = 'shu'
const thirdHorizontalUl = 'thu'
const firstVerticalUl = 'fvu'
const secondVerticalUl = 'svu'
const thirdVerticalUl = 'tvu'
// li's
const firstPostOfFirstHorizontalAuthor = '1hl'
const secondPostOfFirstHorizontalAuthor = '2hl'
const thirdPostOfFirstHorizontalAuthor = '3hl'
const firstPostOfSecondHorizontalAuthor = '4hl'
const secondPostOfSecondHorizontalAuthor = '5hl'
const thirdPostOfSecondHorizontalAuthor = '6hl'
const firstPostOfThirdHorizontalAuthor = '7hl'
const secondPostOfThirdHorizontalAuthor = '8hl'
const thirdPostOfThirdHorizontalAuthor = '9hl'
const firstPostOfFirstVerticalAuthor = '1vl'
const secondPostOfFirstVerticalAuthor = '2vl'
const thirdPostOfFirstVerticalAuthor = '3vl'
const firstPostOfSecondVerticalAuthor = '4vl'
const secondPostOfSecondVerticalAuthor = '5vl'
const thirdPostOfSecondVerticalAuthor = '6vl'
const firstPostOfThirdVerticalAuthor = '7vl'
const secondPostOfThirdVerticalAuthor = '8vl'
const thirdPostOfThirdVerticalAuthor = '9vl'
// blocks
const firstHorizontalBlock = 'fha'
const secondHorizontalBlock = 'sha'
const thirdHorizontalBlock = 'tha'
const firstVerticalBlock = 'fva'
const secondVerticalBlock = 'sva'
const thirdVerticalBlock = 'tva'

